### ISSUE TITLE
Eliminate need for ssh command

### ISSUE THREAD

**Issue by ahmetalpbalkan** [boot2docker/boot2docker-cli#359]
This severely damages boot2docker experience on Windows (cmd.exe/powershell)

Many boot2docker commands require ssh.exe to be in %PATH% and some even mysteriously fail and you need `-v` to see the missing ssh.exe failure... 

Current solution is to **add msysgit's bin\ folder to the PATH** by every time you start a shell:

	$Env:Path = "${Env:Path};c:\Program Files (x86)\Git\bin" // on PowerShell

or

	set PATH=%PATH%;"c:\Program Files (x86)\Git\bin" // on Command Prompt (cmd.exe)

This is a crappy experience for users running outside msys (= most windows users).

If we can eliminate need to `ssh.exe` we can have a **way better experience** on Windows! It might be possible with experimental golang `crypto/ssh` package. (`docker-machine` is also tackling the same problem):

* https://github.com/docker/machine/issues/555
* https://github.com/docker/machine/issues/730

@tianon wdyt? I can take a look if the idea sounds sane and maybe we can land for 1.6? Otherwise b2d experience outside msys is a bit crappy because you need to add ssh.exe to PATH all the time.

**Comment by tianon** [comment]
I think it's an interesting idea, but there's no way I'd be comfortable landing it in 1.6, even if a PR implementing it was already open.

Right now, the "canonical" way to run "`boot2docker.exe`" is via an msysGit `bash` shell, which will mean `ssh` in the `PATH`.  In the future, I think we should definitely look into this though, especially if `docker-machine` actually lands a good implementation (since they'll have more people testing to make sure it's reasonably feature-complete).

**Comment by ahmetalpbalkan** [comment]
@tianon hmm yeah, the only reason I brought up this is even running `boot2docker shellinit` on cmd.exe/powershell.exe requires `ssh` and we don't print cmd/PS instructions on msysGit.

I'll probably look forward to implement this for 1.7.

**Comment by RomanSaveljev** [comment]
Let us not forget that native Windows client for Docker is (allegedly) coming...

**Comment by ahmetb** [comment]
things are better nowadays; closing.
